apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-4jlc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-4jlc
    app.kubernetes.io/part-of: pet-clinic-e2e-gtqpepirqd
  name: devfile-sample-code-with-quarkus-4jlc
  namespace: has-e2e-public-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-4jlc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-4jlc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:0b0b11562edc17d51c540c6dba7acadeff3252b441b169bafab2dcfc3b74a914
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
