apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-4jlc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-4jlc
    app.kubernetes.io/part-of: pet-clinic-e2e-gtqpepirqd
  name: devfile-sample-code-with-quarkus-4jlc
  namespace: has-e2e-public-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-code-with-quarkus-4jlc
    weight: null
status: {}
